version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "iwnfy"
    ports:
      - "3306:3306"
    volumes:
      - /Users/frederico.belisario/Desenvolvimento/workspace/per/docker/volume:/var/lib/mysql

    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
